import {
  pgTable,
  text,
  uuid,
  timestamp,
  pgEnum,
  numeric,
  boolean,
  json,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";
import { leads } from "./crm";
import { quotes } from "./quotes";

export const contractStatusEnum = pgEnum("contract_status", [
  "draft",
  "sent",
  "signed",
  "active",
  "expired",
  "cancelled",
]);

export const contractTemplates = pgTable("contract_templates", {
  id: uuid("id").primaryKey().defaultRandom(),
  language: text("language").notNull().default("en"),
  title: text("title").notNull(),
  category: text("category").notNull().default("general"),
  content: text("content").notNull(),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const contracts = pgTable(
  "contracts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => usersTable.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
    quoteId: uuid("quote_id").references(() => quotes.id, {
      onDelete: "set null",
    }),
    contractNumber: text("contract_number").notNull(),
    title: text("title").notNull(),
    clientName: text("client_name").notNull(),
    clientEmail: text("client_email"),
    clientPhone: text("client_phone"),
    clientCompany: text("client_company"),
    clientAddress: text("client_address"),
    eventType: text("event_type"),
    eventDate: timestamp("event_date"),
    eventLocation: text("event_location"),
    eventStartTime: text("event_start_time"),
    eventEndTime: text("event_end_time"),
    setupTime: text("setup_time"),
    pickupTime: text("pickup_time"),
    packageName: text("package_name"),
    rentalDuration: text("rental_duration"),
    includedPrints: text("included_prints"),
    rentalPrice: numeric("rental_price", { precision: 12, scale: 2 }),
    optionsPrice: numeric("options_price", { precision: 12, scale: 2 }),
    deliveryFees: numeric("delivery_fees", { precision: 12, scale: 2 }),
    discountAmount: numeric("discount_amount", { precision: 12, scale: 2 }),
    taxRate: numeric("tax_rate", { precision: 5, scale: 2 }),
    depositAmount: numeric("deposit_amount", { precision: 12, scale: 2 }),
    depositMethod: text("deposit_method"),
    depositConditions: text("deposit_conditions"),
    depositReturn: text("deposit_return"),
    paymentTerms: text("payment_terms"),
    cancellationTerms: text("cancellation_terms"),
    signaturePlace: text("signature_place"),
    equipmentDescription: text("equipment_description"),
    equipmentIds: json("equipment_ids").$type<string[]>(),
    digitalGallery: boolean("digital_gallery").default(false),
    customTemplate: boolean("custom_template").default(false),
    deliveryIncluded: boolean("delivery_included").default(false),
    setupIncluded: boolean("setup_included").default(false),
    operatorIncluded: boolean("operator_included").default(false),
    optionsList: text("options_list"),
    currency: text("currency"),
    language: text("language"),
    status: contractStatusEnum("status").notNull().default("draft"),
    content: text("content").notNull().default(""),
    value: numeric("value", { precision: 12, scale: 2 }).notNull().default("0"),
    startDate: timestamp("start_date"),
    endDate: timestamp("end_date"),
    signedAt: timestamp("signed_at"),
    sentAt: timestamp("sent_at"),
    notes: text("notes"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("contracts_user_contract_number_unique").on(t.userId, t.contractNumber)],
);
